
def options(opt):
    opt.load('g++')

def configure(conf):
    conf.load('g++')

    conf.env.CXXFLAGS_XNET_TEST = ['-std=c++11']
    conf.env.INCLUDES_XNET_TEST += ['../', '../event_based']
    conf.env.INCLUDES_GTEST = ['/usr/src/gtest']
    conf.env.LIB_GTEST = ['pthread']

def build(bld):
    bld (
        rule = 'wget -O src/test/events20051219T171855_driving_pasa_freeway.mat.dat https://www.ini.uzh.ch/~tobi/dvs/events20051219T171855%20driving%20pasa%20freeway.mat.dat',
        target = 'events20051219T171855_driving_pasa_freeway.mat.dat'
    )

    bld.shlib (
        source = [bld.root.find_node('/usr/src/gtest/src/gtest-all.cc')],
        target = 'gtest',
        use = 'GTEST',
        install_path = 'lib',
    )

    bld.program (
        source = 'aer_read_in_test.cpp',
        target = 'aer_test_in_test',
        use = ['XNET_TEST','gtest'],
        install_path = 'bin/tests',
    )

    bld.program (
        source = 'simple_transmit.cpp',
        target = 'simple_transmit',
        use = ['XNET_TEST','gtest','xnetevent'],
        install_path = 'bin/tests',
    )

    bld.program (
        source = 'random_init.cpp',
        target = 'random_init',
        use = ['XNET_TEST','gtest','xnetevent'],
        install_path = 'bin/tests',
    )

    bld.program (
        source = 'test_ball_trajectory.cpp',
        target = 'ball_trajectory',
        use = ['XNET_TEST','gtest','xnetevent'],
        install_path = 'bin/tests',
    )
